### Importing the Dependencies

In [1]:
import numpy as np
import pandas as pd

### Read the CSV files

In [2]:
books = pd.read_csv(r"D:\OneDrive - GroupM Bangladesh\Machine Learning Projects\Recommender Systems\1. Book Recommendation System\Books.csv")
ratings = pd.read_csv(r"D:\OneDrive - GroupM Bangladesh\Machine Learning Projects\Recommender Systems\1. Book Recommendation System\Ratings.csv")
users = pd.read_csv(r"D:\OneDrive - GroupM Bangladesh\Machine Learning Projects\Recommender Systems\1. Book Recommendation System\Users.csv")

C:\Users\Sadia Tahsin\AppData\Local\Temp\ipykernel_5720\1264237318.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books = pd.read_csv(r"D:\OneDrive - GroupM Bangladesh\Machine Learning Projects\Recommender Systems\1. Book Recommendation System\Books.csv")

### Checking the first 5 rows of each dataset

In [3]:
books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [4]:
users.head()

   User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [5]:
ratings.head()

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

In [6]:
print(books.shape)
print(users.shape)
print(ratings.shape)

(271360, 8)
(278858, 3)
(1149780, 3)

### Checking the null values

In [7]:
books.isnull().sum()

ISBN                   0
Book-Title             0
Book-Author            2
Year-Of-Publication    0
Publisher              2
Image-URL-S            0
Image-URL-M            0
Image-URL-L            3
dtype: int64

In [8]:
users.isnull().sum()

User-ID          0
Location         0
Age         110762
dtype: int64

In [9]:
ratings.isnull().sum()

User-ID        0
ISBN           0
Book-Rating    0
dtype: int64

### Checking duplicated values

In [10]:
books.duplicated().sum()

0

In [11]:
users.duplicated().sum()

0

In [12]:
ratings.duplicated().sum()

0

### Popularity Based Recommender System

In [13]:
books_with_ratings = ratings.merge(books, on = "ISBN")

In [14]:
books_with_ratings.groupby('Book-Title').count()

,User-ID,ISBN,Book-Rating,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
Book-Title,,,,,,,,,
"A Light in the Storm: The Civil War Diary of Amelia Martin, Fenwick Island, Delaware, 1861 (Dear America)",4,4,4,4,4,4,4,4,4
Always Have Popsicles,1,1,1,1,1,1,1,1,1
Apple Magic (The Collector's series),1,1,1,1,1,1,1,1,1
"Ask Lily (Young Women of Faith: Lily Series, Book 5)",1,1,1,1,1,1,1,1,1
Beyond IBM: Leadership Marketing and Finance for the 1990s,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...
Ã?Â?lpiraten.,2,2,2,2,2,2,2,2,2
Ã?Â?rger mit Produkt X. Roman.,4,4,4,4,4,4,4,4,4
Ã?Â?sterlich leben.,1,1,1,1,1,1,1,1,1
Ã?Â?stlich der Berge.,3,3,3,3,3,3,3,3,3
Ã?Â?thique en toc,2,2,2,2,2,2,2,2,2

In [15]:
#Grouping books based on count of ratings

num_ratings = books_with_ratings.groupby('Book-Title').count()['Book-Rating'].reset_index()
num_ratings.rename(columns={'Book-Rating':'num_ratings'},inplace=True)
num_ratings

                                               Book-Title  num_ratings
0        A Light in the Storm: The Civil War Diary of ...            4
1                                   Always Have Popsicles            1
2                    Apple Magic (The Collector's series)            1
3        Ask Lily (Young Women of Faith: Lily Series, ...            1
4        Beyond IBM: Leadership Marketing and Finance ...            1
...                                                   ...          ...
241066                                      Ã?Â?lpiraten.            2
241067                     Ã?Â?rger mit Produkt X. Roman.            4
241068                                Ã?Â?sterlich leben.            1
241069                              Ã?Â?stlich der Berge.            3
241070                                  Ã?Â?thique en toc            2

[241071 rows x 2 columns]

In [16]:
# Grouping the books based on avg. rating

avg_rating = books_with_ratings.groupby('Book-Title')['Book-Rating'].mean().reset_index()
avg_rating.rename(columns={'Book-Rating':'Avg. Rating'},inplace=True)
avg_rating

                                               Book-Title  Avg. Rating
0        A Light in the Storm: The Civil War Diary of ...     2.250000
1                                   Always Have Popsicles     0.000000
2                    Apple Magic (The Collector's series)     0.000000
3        Ask Lily (Young Women of Faith: Lily Series, ...     8.000000
4        Beyond IBM: Leadership Marketing and Finance ...     0.000000
...                                                   ...          ...
241066                                      Ã?Â?lpiraten.     0.000000
241067                     Ã?Â?rger mit Produkt X. Roman.     5.250000
241068                                Ã?Â?sterlich leben.     7.000000
241069                              Ã?Â?stlich der Berge.     2.666667
241070                                  Ã?Â?thique en toc     4.000000

[241071 rows x 2 columns]

In [17]:
#merging both num_ratings and Avg. Rating
popular_df = num_ratings.merge(avg_rating)
popular_df

,Book-Title,num_ratings,Avg. Rating
0,A Light in the Storm: The Civil War Diary of ...,4,2.250000
1,Always Have Popsicles,1,0.000000
2,Apple Magic (The Collector's series),1,0.000000
3,"Ask Lily (Young Women of Faith: Lily Series, ...",1,8.000000
4,Beyond IBM: Leadership Marketing and Finance ...,1,0.000000
...,...,...,...
241066,Ã?Â?lpiraten.,2,0.000000
241067,Ã?Â?rger mit Produkt X. Roman.,4,5.250000
241068,Ã?Â?sterlich leben.,1,7.000000
241069,Ã?Â?stlich der Berge.,3,2.666667
241070,Ã?Â?thique en toc,2,4.000000

In [18]:
#selecting the books with 250 or more than 250 ratings
popular_df = popular_df[popular_df['num_ratings']>=250].sort_values(['Avg. Rating'],ascending=False).head(50)

In [19]:
popular_df

,Book-Title,num_ratings,Avg. Rating
80434,Harry Potter and the Prisoner of Azkaban (Book 3),428,5.852804
80422,Harry Potter and the Goblet of Fire (Book 4),387,5.824289
80441,Harry Potter and the Sorcerer's Stone (Book 1),278,5.737410
80426,Harry Potter and the Order of the Phoenix (Boo...,347,5.501441
80414,Harry Potter and the Chamber of Secrets (Book 2),556,5.183453
191612,The Hobbit : The Enchanting Prelude to The Lor...,281,5.007117
187377,The Fellowship of the Ring (The Lord of the Ri...,368,4.948370
80445,Harry Potter and the Sorcerer's Stone (Harry P...,575,4.895652
211384,"The Two Towers (The Lord of the Rings, Part 2)",260,4.880769
219741,To Kill a Mockingbird,510,4.700000
183573,The Da Vinci Code,898,4.642539
187880,The Five People You Meet in Heaven,430,4.551163
180556,The Catcher in the Rye,449,4.545657
196326,The Lovely Bones: A Novel,1295,4.468726
764,1984,284,4.454225
144165,Prodigal Summer: A Novel,253,4.450593
128670,Neverwhere,265,4.449057
206502,The Secret Life of Bees,774,4.447028
168719,Stupid White Men ...and Other Sorry Excuses fo...,283,4.356890
223135,"Tuesdays with Morrie: An Old Man, a Young Man,...",493,4.354970
204387,The Red Tent (Bestselling Backlist),723,4.334716
191589,The Hitchhiker's Guide to the Galaxy,268,4.328358
129379,Nickel and Dimed: On (Not) Getting By in America,335,4.289552
93381,Into the Wild,252,4.273810
63867,Fahrenheit 451,409,4.264059
74750,Girl with a Pearl Earring,526,4.218631
136145,Outlander,283,4.173145
233370,Where the Heart Is (Oprah's Book Club (Paperba...,585,4.105983
156102,Seabiscuit: An American Legend,275,4.098182
107962,Life of Pi,664,4.088855
176845,The Bean Trees,389,4.087404
2281,"A Child Called \It\"": One Child's Courage to S...",265,4.086792
8434,ANGELA'S ASHES,279,4.075269
76343,Good in Bed,490,4.055102
64931,Fast Food Nation: The Dark Side of the All-Ame...,321,4.037383
12700,American Gods,302,4.006623
161645,Skipping Christmas,322,4.006211
105777,Left Behind: A Novel of the Earth's Last Days ...,318,4.003145
189551,"The Golden Compass (His Dark Materials, Book 1)",336,4.000000
181679,The Color Purple,314,3.964968
160336,Silence of the Lambs,256,3.960938
8752,About a Boy,262,3.900763
158138,Seven Up (A Stephanie Plum Novel),278,3.888489
175097,The Alchemist: A Fable About Following Your Dream,266,3.875940
80069,Hard Eight : A Stephanie Plum Novel (A Stephan...,269,3.825279
170101,Suzanne's Diary for Nicholas,457,3.820569
111073,Lord of the Flies,259,3.818533
5664,A Prayer for Owen Meany,413,3.796610
212070,"The Vampire Lestat (Vampire Chronicles, Book II)",301,3.777409
233851,White Oleander : A Novel (Oprah's Book Club),356,3.772472

In [20]:
#merging data based on book information

popular_df = popular_df.merge(books,on='Book-Title').drop_duplicates('Book-Title')[['Book-Title','ISBN','Book-Author','Image-URL-M','Avg. Rating','num_ratings']]

In [43]:
popular_df

,Book-Title,ISBN,Book-Author,Image-URL-M,Avg. Rating,num_ratings
0,Harry Potter and the Prisoner of Azkaban (Book 3),0439136350,J. K. Rowling,http://images.amazon.com/images/P/0439136350.0...,5.852804,428
3,Harry Potter and the Goblet of Fire (Book 4),0439139597,J. K. Rowling,http://images.amazon.com/images/P/0439139597.0...,5.824289,387
5,Harry Potter and the Sorcerer's Stone (Book 1),0590353403,J. K. Rowling,http://images.amazon.com/images/P/0590353403.0...,5.737410,278
9,Harry Potter and the Order of the Phoenix (Boo...,043935806X,J. K. Rowling,http://images.amazon.com/images/P/043935806X.0...,5.501441,347
13,Harry Potter and the Chamber of Secrets (Book 2),0439064872,J. K. Rowling,http://images.amazon.com/images/P/0439064872.0...,5.183453,556
16,The Hobbit : The Enchanting Prelude to The Lor...,0345339681,J.R.R. TOLKIEN,http://images.amazon.com/images/P/0345339681.0...,5.007117,281
17,The Fellowship of the Ring (The Lord of the Ri...,0345339703,J.R.R. TOLKIEN,http://images.amazon.com/images/P/0345339703.0...,4.948370,368
26,Harry Potter and the Sorcerer's Stone (Harry P...,059035342X,J. K. Rowling,http://images.amazon.com/images/P/059035342X.0...,4.895652,575
28,"The Two Towers (The Lord of the Rings, Part 2)",0345339711,J.R.R. TOLKIEN,http://images.amazon.com/images/P/0345339711.0...,4.880769,260
39,To Kill a Mockingbird,0446310786,Harper Lee,http://images.amazon.com/images/P/0446310786.0...,4.700000,510
47,The Da Vinci Code,0385504209,Dan Brown,http://images.amazon.com/images/P/0385504209.0...,4.642539,898
53,The Five People You Meet in Heaven,0786868716,Mitch Albom,http://images.amazon.com/images/P/0786868716.0...,4.551163,430
55,The Catcher in the Rye,0316769487,J.D. Salinger,http://images.amazon.com/images/P/0316769487.0...,4.545657,449
62,The Lovely Bones: A Novel,0316666343,Alice Sebold,http://images.amazon.com/images/P/0316666343.0...,4.468726,1295
63,1984,0451524934,George Orwell,http://images.amazon.com/images/P/0451524934.0...,4.454225,284
72,Prodigal Summer: A Novel,0060959037,Barbara Kingsolver,http://images.amazon.com/images/P/0060959037.0...,4.450593,253
73,Neverwhere,0380789019,Neil Gaiman,http://images.amazon.com/images/P/0380789019.0...,4.449057,265
78,The Secret Life of Bees,0142001740,Sue Monk Kidd,http://images.amazon.com/images/P/0142001740.0...,4.447028,774
84,Stupid White Men ...and Other Sorry Excuses fo...,0060392452,Michael Moore,http://images.amazon.com/images/P/0060392452.0...,4.356890,283
85,"Tuesdays with Morrie: An Old Man, a Young Man,...",0385484518,MITCH ALBOM,http://images.amazon.com/images/P/0385484518.0...,4.354970,493
88,The Red Tent (Bestselling Backlist),0312195516,Anita Diamant,http://images.amazon.com/images/P/0312195516.0...,4.334716,723
89,The Hitchhiker's Guide to the Galaxy,0671461494,Douglas Adams,http://images.amazon.com/images/P/0671461494.0...,4.328358,268
98,Nickel and Dimed: On (Not) Getting By in America,0805063897,Barbara Ehrenreich,http://images.amazon.com/images/P/0805063897.0...,4.289552,335
100,Into the Wild,0385486804,Jon Krakauer,http://images.amazon.com/images/P/0385486804.0...,4.273810,252
103,Fahrenheit 451,3257208626,Ray Bradbury,http://images.amazon.com/images/P/3257208626.0...,4.264059,409
116,Girl with a Pearl Earring,0452282152,Tracy Chevalier,http://images.amazon.com/images/P/0452282152.0...,4.218631,526
117,Outlander,0440222915,DIANA GABALDON,http://images.amazon.com/images/P/0440222915.0...,4.173145,283
123,Where the Heart Is (Oprah's Book Club (Paperba...,0446672211,Billie Letts,http://images.amazon.com/images/P/0446672211.0...,4.105983,585
124,Seabiscuit: An American Legend,0449005615,LAURA HILLENBRAND,http://images.amazon.com/images/P/0449005615.0...,4.098182,275
126,Life of Pi,0151008116,Yann Martel,http://images.amazon.com/images/P/0151008116.0...,4.088855,664
130,The Bean Trees,0060915544,Barbara Kingsolver,http://images.amazon.com/images/P/0060915544.0...,4.087404,389
133,"A Child Called \It\"": One Child's Courage to S...",1558743669,Dave Pelzer,http://images.amazon.com/images/P/1558743669.0...,4.086792,265
135,ANGELA'S ASHES,0684874350,Frank McCourt,http://images.amazon.com/images/P/0684874350.0...,4.075269,279
137,Good in Bed,0743418174,Jennifer Weiner,http://images.amazon.com/images/P/0743418174.0...,4.055102,490
139,Fast Food Nation: The Dark Side of the All-Ame...,0060938455,Eric Schlosser,http://images.amazon.com/images/P/0060938455.0...,4.037383,321
140,American Gods,0380789035,Neil Gaiman,http://images.amazon.com/images/P/0380789035.0...,4.006623,302
141,Skipping Christmas,0385505833,JOHN GRISHAM,http://images.amazon.com/images/P/0385505833.0...,4.006211,322
147,Left Behind: A Novel of the Earth's Last Days ...,0842329129,Tim Lahaye,http://images.amazon.com/images/P/0842329129.0...,4.003145,318
149,"The Golden Compass (His Dark Materials, Book 1)",037582345X,PHILIP PULLMAN,http://images.amazon.com/images/P/037582345X.0...,4.000000,336
157,The Color Purple,0671617028,Alice Walker,http://images.amazon.com/images/P/0671617028.0...,3.964968,314
163,Silence of the Lambs,0312924585,Thomas Harris,http://images.amazon.com/images/P/0312924585.0...,3.960938,256
166,About a Boy,1573227331,Nick Hornby,http://images.amazon.com/images/P/1573227331.0...,3.900763,262
173,Seven Up (A Stephanie Plum Novel),0312265840,Janet Evanovich,http://images.amazon.com/images/P/0312265840.0...,3.888489,278
175,The Alchemist: A Fable About Following Your Dream,0062502174,Paulo Coelho,http://images.amazon.com/images/P/0062502174.0...,3.875940,266
177,Hard Eight : A Stephanie Plum Novel (A Stephan...,0312983867,Janet Evanovich,http://images.amazon.com/images/P/0312983867.0...,3.825279,269
182,Suzanne's Diary for Nicholas,0316969443,James Patterson,http://images.amazon.com/images/P/0316969443.0...,3.820569,457
186,Lord of the Flies,0399501487,William Gerald Golding,http://images.amazon.com/images/P/0399501487.0...,3.818533,259
192,A Prayer for Owen Meany,0345361792,John Irving,http://images.amazon.com/images/P/0345361792.0...,3.796610,413
194,"The Vampire Lestat (Vampire Chronicles, Book II)",0345313860,ANNE RICE,http://images.amazon.com/images/P/0345313860.0...,3.777409,301
195,White Oleander : A Novel (Oprah's Book Club),0316284955,Janet Fitch,http://images.amazon.com/images/P/0316284955.0...,3.772472,356

### Collaborative Filtering Based Recommender System

In [21]:
x = books_with_ratings.groupby('User-ID').count()['Book-Rating'] > 200
exact_readers = x[x].index

In [22]:
filtered_rating = books_with_ratings[books_with_ratings['User-ID'].isin(exact_readers)]

In [23]:
y = filtered_rating.groupby('Book-Title').count()['Book-Rating']>=50
famous_books = y[y].index

In [24]:
famous_books

Index(['1984', '1st to Die: A Novel', '2nd Chance', '4 Blondes',
       'A Bend in the Road', 'A Case of Need',
       'A Child Called \It\": One Child's Courage to Survive"',
       'A Civil Action', 'A Day Late and a Dollar Short', 'A Fine Balance',
       ...
       'Winter Solstice', 'Wish You Well', 'Without Remorse',
       'Wizard and Glass (The Dark Tower, Book 4)', 'Wuthering Heights',
       'Year of Wonders', 'You Belong To Me',
       'Zen and the Art of Motorcycle Maintenance: An Inquiry into Values',
       'Zoya', '\O\" Is for Outlaw"'],
      dtype='object', name='Book-Title', length=706)

In [25]:
final_ratings = filtered_rating[filtered_rating['Book-Title'].isin(famous_books)]

In [26]:
final_ratings.drop_duplicates()

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
63,278418,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
65,3363,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
66,7158,0446520802,10,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
69,11676,0446520802,10,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
74,23768,0446520802,6,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
...,...,...,...,...,...,...,...,...,...,...
1026724,266865,0531001725,10,The Catcher in the Rye,Jerome David Salinger,1973,Scholastic Library Pub,http://images.amazon.com/images/P/0531001725.0...,http://images.amazon.com/images/P/0531001725.0...,http://images.amazon.com/images/P/0531001725.0...
1027923,269566,0670809381,0,Echoes,Maeve Binchy,1986,Penguin USA,http://images.amazon.com/images/P/0670809381.0...,http://images.amazon.com/images/P/0670809381.0...,http://images.amazon.com/images/P/0670809381.0...
1028777,271284,0440910927,0,The Rainmaker,John Grisham,1995,Island,http://images.amazon.com/images/P/0440910927.0...,http://images.amazon.com/images/P/0440910927.0...,http://images.amazon.com/images/P/0440910927.0...
1029070,271705,B0001PIOX4,0,Fahrenheit 451,Ray Bradbury,1993,Simon &amp; Schuster,http://images.amazon.com/images/P/B0001PIOX4.0...,http://images.amazon.com/images/P/B0001PIOX4.0...,http://images.amazon.com/images/P/B0001PIOX4.0...
1030868,275970,1586210661,9,Me Talk Pretty One Day,David Sedaris,2001,Time Warner Audio Major,http://images.amazon.com/images/P/1586210661.0...,http://images.amazon.com/images/P/1586210661.0...,http://images.amazon.com/images/P/1586210661.0...

In [38]:
final_ratings

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
63,278418,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
65,3363,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
66,7158,0446520802,10,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
69,11676,0446520802,10,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
74,23768,0446520802,6,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
...,...,...,...,...,...,...,...,...,...,...
1026724,266865,0531001725,10,The Catcher in the Rye,Jerome David Salinger,1973,Scholastic Library Pub,http://images.amazon.com/images/P/0531001725.0...,http://images.amazon.com/images/P/0531001725.0...,http://images.amazon.com/images/P/0531001725.0...
1027923,269566,0670809381,0,Echoes,Maeve Binchy,1986,Penguin USA,http://images.amazon.com/images/P/0670809381.0...,http://images.amazon.com/images/P/0670809381.0...,http://images.amazon.com/images/P/0670809381.0...
1028777,271284,0440910927,0,The Rainmaker,John Grisham,1995,Island,http://images.amazon.com/images/P/0440910927.0...,http://images.amazon.com/images/P/0440910927.0...,http://images.amazon.com/images/P/0440910927.0...
1029070,271705,B0001PIOX4,0,Fahrenheit 451,Ray Bradbury,1993,Simon &amp; Schuster,http://images.amazon.com/images/P/B0001PIOX4.0...,http://images.amazon.com/images/P/B0001PIOX4.0...,http://images.amazon.com/images/P/B0001PIOX4.0...
1030868,275970,1586210661,9,Me Talk Pretty One Day,David Sedaris,2001,Time Warner Audio Major,http://images.amazon.com/images/P/1586210661.0...,http://images.amazon.com/images/P/1586210661.0...,http://images.amazon.com/images/P/1586210661.0...

In [28]:
pt = final_ratings.pivot_table(index='Book-Title',columns='User-ID',values='Book-Rating')

In [29]:
pt.fillna(0,inplace=True)

In [30]:
#importing cosine_similarity
from sklearn.metrics.pairwise import cosine_similarity

In [31]:
similarity_scores = cosine_similarity(pt)

In [32]:
similarity_scores.shape

(706, 706)

In [33]:
def recommend(book_name):
        index = np.where(pt.index==book_name)[0][0]
        similar_items = sorted(list(enumerate(similarity_scores[index])),key=lambda x:x[1],reverse=True) [1:6]

        for i in similar_items:
            print(pt.index[i[0]])

In [34]:
recommend('The Notebook')

A Walk to Remember
The Rescue
One Door Away from Heaven
Toxin
The Five People You Meet in Heaven

In [42]:
import pickle
pickle.dump(popular_df,open('popular.pkl','wb'))

In [44]:
books.drop_duplicates('Book-Title')

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...
...,...,...,...,...,...,...,...,...
271354,0449906736,Flashpoints: Promise and Peril in a New World,Robin Wright,1993,Ballantine Books,http://images.amazon.com/images/P/0449906736.0...,http://images.amazon.com/images/P/0449906736.0...,http://images.amazon.com/images/P/0449906736.0...
271356,0525447644,From One to One Hundred,Teri Sloat,1991,Dutton Books,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...
271357,006008667X,Lily Dale : The True Story of the Town that Ta...,Christine Wicker,2004,HarperSanFrancisco,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...
271358,0192126040,Republic (World's Classics),Plato,1996,Oxford University Press,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...
271359,0767409752,A Guided Tour of Rene Descartes' Meditations o...,Christopher Biffle,2000,McGraw-Hill Humanities/Social Sciences/Languages,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...

In [45]:
pickle.dump(pt,open('pt.pkl','wb'))
pickle.dump(books,open('books.pkl','wb'))
pickle.dump(similarity_scores,open('similarity_scores.pkl','wb'))